feat: 2px slideshow section
makeswift/vibes pull request #125
Opened 2024-08-12 08:35 UTC by LHDi

2024-08-12 14:44 UTC, freadbaker requested changes
@LHDi This looks good! Two things I missed from the Figma prototype, though: 

1. The ability to go to next slide when clicking anywhere in the screen
2. The ability to control the slides with the arrow keys on my keyboard.

2024-08-13 08:38 UTC, LHDi commented
> The ability to go to next slide when clicking anywhere in the screen
is this addressed anywhere @freadbaker 🤔

2024-08-13 11:25 UTC, LHDi commented
@freadbaker please take another look 🙏

2024-08-13 12:13 UTC, freadbaker commented on apps/web/vibes/2px/components/slideshow-section/index.tsx
> +        <h2 className="mb-2 font-mono leading-[1.375rem] tracking-[0.02em]">
This should be uppercase.

2024-08-13 12:15 UTC, freadbaker approved these changes
Great work!

2024-08-13 12:17 UTC, merged