fix: slide not in view when element inside is focused
makeswift/vibes pull request #354
Opened 2024-11-25 20:42 UTC by hunterbecton

## What/Why?

- Fixes issue where the slide was not visible when the button was focused
- Replaces `text-pretty` with `text-balance` for text-wrapping

## Testing

https://github.com/user-attachments/assets/96060633-40b8-4585-8572-5d4d0019c6f1

2024-11-25 21:17 UTC, migueloller requested changes
Looks like there's changes in `pnpm-lock.yaml` that shouldn't be there?

Also, can we `git rebase` and squash the two commits? Can also do this at merge time in GitHub using "Squash and merge".

2024-11-25 21:28 UTC, migueloller commented
Also, it looks like we didn't pull in the `text-balance` change

2024-11-26 02:47 UTC, hunterbecton reviewed
Added the `text-balance` Tailwind class.

2024-11-26 20:24 UTC, migueloller approved these changes

2024-11-26 21:21 UTC, merged